security:
  basic:
    enabled: false
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/appspringboot
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: false
    
    
mybatis:
     # 
  config-location: classpath:mybatis/mybatis-config.xml #This is the main profile path
  mapper-location: classpath:mybatis/mapper/*.xml   #Configuration of database mapping file
  type-aliases-package: com.buuth.appspringboot.entity
     #mapper.xmlLocation
  mapper-locations: classpath:mybatis/mapper/*.xml
